# Generated by Django 2.2 on 2019-04-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('race', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=15)),
                ('payer_code', models.CharField(max_length=3)),
            ],
        ),
    ]
